---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: project-draft-db
  labels:
    app: project-draft-db
spec:
  serviceName: "project-draft-db"
  replicas: 1
  selector:
    matchLabels:
      app: project-draft-db
  template:
    metadata:
      labels:
        app: project-draft-db
    spec:
      containers:
        - name: project-draft-db
          image: docker.io/library/postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
          livenessProbe:
            tcpSocket:
              port: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: project-draft-db
spec:
  selector:
    app: project-draft-db
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-draft
  labels:
    app: project-draft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-draft
  template:
    metadata:
      labels:
        app: project-draft
    spec:
      containers:
        - name: project-draft
          image: project-draft:release
          imagePullPolicy: Never
          command: ["./script/run"]
          ports:
            - containerPort: 3000
          env:
            - name: APP_APPLICATION__HOST
              value: 0.0.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: project-draft
spec:
  type: LoadBalancer
  selector:
    app: project-draft
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-draft-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: project-draft
                port:
                  number: 3000
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-draft-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: ImplementationSpecific
            path: /api(/|$)(.*)
            backend:
              service:
                name: backend
                port:
                  number: 8000
