apiVersion: v1
kind: ConfigMap
metadata:
  name: microtutor-backend-config
data:
  NODE_ENV: "production"
  DB_SSL: "false"
  CORS_ORIGIN: "http://localhost,http://127.0.0.1"
  FRONTEND_BASE_URL: "http://localhost"
  LLM_BASE_URL: "http://ollama:11434/v1"
  LLM_MODEL: "qwen2.5:0.5b"
  COOKIE_SECURE: "false"
