apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microtutor
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - secrets.yaml
  - postgres-init-configmap.yaml
  - postgres-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ollama-init-configmap.yaml
  - ollama-deployment.yaml
