apiVersion: v1
kind: Secret
metadata:
  name: microtutor-db-secret
type: Opaque
stringData:
  POSTGRES_USER: myapp_user
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: myapp_db
  DATABASE_URL: postgresql://myapp_user:secret@db:5432/myapp_db
