apiVersion: v1
kind: ConfigMap
metadata:
  name: microtutor-backend-config
data:
  NODE_ENV: "development"
  PORT: "3000"
  DB_SSL: "false"
  CORS_ORIGIN: "http://localhost:8080,http://localhost,http://127.0.0.1,http://35.184.217.136,http://35.184.217.136:80,https://34.10.159.172,https://34.10.159.172:443"
  FRONTEND_BASE_URL: "https://34.10.159.172"
  LLM_BASE_URL: "http://ollama:11434/v1"
  LLM_MODEL: "qwen2.5:0.5b"
  COOKIE_SECURE: "true"
